default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  timeout: 5000

development:
    <<: *default
    adapter: mysql2
    database: herp
    encoding: utf8
    username: admin
    password: admin
    host: localhost

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: mysql2
  database: <%= ENV['sql_db'] %>
  encoding: utf8
  username: <%= ENV['sql_user'] %>
  password: <%= ENV['sql_pass'] %>
  #  socket: ENV['sql_socket']
  host: 127.0.0.1
  port: 3306
