name: deploy-to-kyoshi
on: [push]
jobs:
  deploy-to-kyoshi:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "${{ secrets.ID_RSA }}" > id_rsa'
      - run: chmod 400 ./id_rsa
      - run: ssh -o "StrictHostKeyChecking=no" -i ./id_rsa cicd@herpetology.pro && /home/cicd/herp