name: deploy-to-roku
on: [push]
jobs:
  deploy-to-roku:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "${{ secrets.ID_RSA }}" > id_rsa'
      - run: chmod 400 ./id_rsa
      - run: ssh -o "StrictHostKeyChecking=no" -i ./id_rsa herp@18.222.56.243 source ~/.profile && /home/herp/cicd.sh